create table CATEGORIES(
	CATEGORYID INT PRIMARY KEY IDENTITY(1,1)
	, NAME NVARCHAR(100) NOT NULL
	, [DESCRIPTION] NVARCHAR(500)
	, CREATEDBY INT NOT NULL
	, CREATEDDATE DATE NOT NULL
	, MODIFIEDBY INT
	, MODIFIEDDATE DATE 
	, DELETED INT NOT NULL
)

create table PRODUCTS(
	PRODUCTID INT PRIMARY KEY IDENTITY(1,1)
	, CATEGORYID INT FOREIGN KEY REFERENCES CATEGORIES(CATEGORYID) 
	, NAME NVARCHAR(100) NOT NULL
	, PRICE FLOAT NOT NULL
	, [STATUS] VARCHAR(50) NOT NULL
	, [DESCRIPTION] NVARCHAR(500) 
	, CREATEDBY INT NOT NULL
	, CREATEDDATE DATE NOT NULL
	, MODIFIEDBY INT 
	, MODIFIEDDATE DATE
	, DELETED INT NOT NULL
)

CREATE TABLE CUSTOMERS(
	CUSTOMERID INT PRIMARY KEY IDENTITY(1,1)
	, NAME NVARCHAR(100) NOT NULL
	, BIRTHDAY DATE NOT NULL
	, PHONE VARCHAR(20) NOT NULL
	, MAIL VARCHAR(100) NOT NULL
	, [ADDRESS] NVARCHAR(200) NOT NULL
)